<?php
/**
 * SocialEngine
 *
 * @category   Application_Extensions
 * @package    Blog
 * @copyright  Copyright 2006-2010 Webligo Developments
 * @license    http://www.socialengine.com/license/
 * @author     John
 */
return array(
  '4.8.6' => array(
    'settings/changelog.php' => 'Incremented version',  
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/index/view.tpl' => 'Fixed bug where bullets were not being displayed in description when added via TinyMce Editor',
  ),
  '4.8.2' => array(
    'controllers/AdminSettingsController.php' => 'Corrected a variable name',
    'Model/DbTable/Blogs.php' => 'Corrected a variable name',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
  ),
  '4.8.1' => array(
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
    'Form/Create.php' => 'Added link button to TinyMCE for blog posts',
  ),
  '4.8.0' => array(
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/index/upload-photo.tpl' => 'Image uploads',
  ),
  '4.7.1' => array(
    'Form/Create.php' => 'Restored image uploads',
    'controllers/IndexController.php' => 'Restored image uploads',
  ),
  '4.7.0' => array(
    '/application/languages/en/blog.csv' => 'Added phrases',
    'controllers/IndexController.php' => 'Added posting limits',
    'Form/Admin/Settings/Level.php' => 'Fixed a message',
    'Model/Blog.php' => 'Added getSlug()',
    'views/scripts/index/create.tpl' => 'Minimized Autocompleter.js',
    'views/scripts/index/edit.tpl' => 'Minimized Autocompleter.js',
    'settings/my.sql' => 'Incremented version',
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
  ),
  '4.5.0' => array(
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/index/create.tpl' => 'Setting active class on main menu',
    'views/scripts/index/edit.tpl' => 'Setting active class on main menu',
    'views/scripts/index/list.tpl' => 'Setting active class on main menu',
    'views/scripts/index/manage.tpl' => 'Setting active class on main menu',
    'views/scripts/index/view.tpl' => 'Setting active class on main menu',
    'widgets/browse-menu/Controller.php' => 'Hides menu if only one item',
  ),
  '4.3.0' => array(
    'controllers/IndexController.php' => 'Added new pages to layout editor',
    'settings/changelog.php' => 'Incremented version',
    'settings/install.php' => 'Added new pages to layout editor',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/index/create.tpl' => 'Added new pages to layout editor',
    'views/scripts/index/manage.tpl' => 'Added new pages to layout editor',
  ),
  '4.2.8' => array(
    'Form/Create.php' => 'Add formatting row to tinymce editor',
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
  ),
  '4.2.6' => array(
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
  ),
  '4.2.5' => array(
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/admin-manage/index.tpl' => 'Add support links',
  ),
  '4.2.4' => array(
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.2.3-4.2.4.sql' => 'Added',
    'settings/my.sql' => 'Incremented version',
  ),
  '4.2.3' => array(
    '/application/languages/en/blog.csv' => 'Rewrite Profile viewing and Profile Commenting Options Descriptions',
    'Form/Admin/Settings/Level.php' => 'Added support links in admin panel',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
  ),
  '4.2.2' => array(
    'Model/Blog.php' => 'Fixed declaration compatibility error',
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
  ),
  '4.2.1' => array(
    'controllers/IndexController.php' => 'Fixed error with invalid custom styles',
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
  ),
  '4.2.0' => array(
    'Form/Create.php' => 'Added token to help prevent spam',
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
  ),
  '4.1.8p1' => array(
    'controllers/IndexController.php' => 'Fixed issue with pagination',
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/index/list.tpl' => 'Added missing translation',
  ),
  '4.1.8' => array(
    'controllers/IndexController.php' => 'Added pages to the layout editor',
    'externals/.htaccess' => 'Updated with far-future expires headers for static resources',
    'externals/styles/main.css' => 'Style tweaks for layout editor',
    'Form/Create.php' => 'Added HTML5 autofocus',
    'settings/changelog.php' => 'Incremented version',
    'settings/content.php' => 'Added pages to the layout editor',
    'settings/install.php' => 'Added pages to the layout editor',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/admin-settings/categories.tpl' => 'Added static base URL for CDN support',
    'views/scripts/index/create.tpl' => 'Added static base URL for CDN support',
    'views/scripts/index/edit.tpl' => 'Added static base URL for CDN support',
    'views/scripts/index/index.tpl' => 'Added pages to the layout editor',
    'views/scripts/index/list.tpl' => 'Added pages to the layout editor',
    'views/scripts/index/upload-photo.tpl' => 'Added static base URL for CDN support',
    'views/scripts/index/view.tpl' => 'Added pages to the layout editor',
    'widgets/browse-menu-quick/Controller.php' => 'Added',
    'widgets/browse-menu-quick/index.tpl' => 'Added',
    'widgets/browse-menu/Controller.php' => 'Added',
    'widgets/browse-menu/index.tpl' => 'Added',
    'widgets/browse-search/Controller.php' => 'Added',
    'widgets/browse-search/index.tpl' => 'Added',
    'widgets/gutter-menu/Controller.php' => 'Added',
    'widgets/gutter-menu/index.tpl' => 'Added',
    'widgets/gutter-photo/Controller.php' => 'Added',
    'widgets/gutter-photo/index.tpl' => 'Added',
    'widgets/gutter-search/Controller.php' => 'Added',
    'widgets/gutter-search/index.tpl' => 'Added',
  ),
  '4.1.7' => array(
    '/application/languages/en/blog.csv' => 'Added phrases',
    'Api/Core.php' => 'Merging methods from api to dbtables',
    'controllers/AdminManageController.php' => 'Merging methods from api to dbtables',
    'controllers/AdminSettingsController.php' => 'Merging methods from api to dbtables',
    'controllers/IndexController.php' => 'Merging methods from api to dbtables',
    'Form/Create.php' => 'Minor optimizations',
    'Model/Category.php' => 'Minor optimizations',
    'Model/DbTable/Blogs.php' => 'Minor optimizations',
    'Model/DbTable/Categories.php' => 'Minor optimizations',
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/index/list.tpl' => 'Minor optimizations',
    'views/scripts/index/view.tpl' => 'Minor optimizations',
    'widgets/profile-blogs/Controller.php' => 'Minor optimizations',
  ),
  '4.1.6' => array(
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/index/view.tpl' => 'Fixed PHP notice',
  ),
  '4.1.4' => array(
    '/application/languages/en/blog.csv' => 'Added phrases',
    'controllers/BlogController.php' => 'Added',
    'controllers/IndexController.php' => 'Sets member as subject in list action; Added photo upload action',
    'controllers/SubscriptionController.php' => 'Added',
    'externals/images/subscribe.png' => 'Added',
    'externals/images/unsubscribe.png' => 'Added',
    'externals/styles/main.css' => 'Added styles',
    'externals/styles/mobile.css' => 'Added',
    'Form/Create.php' => 'Added photo upload support',
    'Model/DbTable/Subscriptions.php' => 'Added',
    'Plugin/Core.php' => 'Added menu item for subscriptions',
    'Plugin/Menus.php' => 'Repatch issue with smoothbox not closing after sharing a blog',
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.1.3-4.1.4.sql' => 'Added',
    'settings/my.sql' => 'Incremented version; Inserts menu item for mobile',
    'views/scripts/index/upload-photo.tpl' => 'Added',
    'views/scripts/index/view.tpl' => 'Fixed issue with displaying category',
    'views/scripts/subscription/add.tpl' => 'Added',
    'views/scripts/subscription/remove.tpl' => 'Added',
  ),
  '4.1.3' => array(
    'externals/styles/main.css' => 'The blog gutter background color is now a scaffold constant variable',
    'Plugin/Menus.php' => 'Fixed issue with smoothbox not closing after sharing a blog',
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
  ),
  '4.1.2' => array(
    'Api/Core.php' => 'Fixes issue where filtering blog by tag would give an error',
    'settings/changelog.php' => 'Incremented version',
    'settings/content.php' => 'Added configuration options to widgets',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
    'widgets/list-popular-blogs/Controller.php' => 'Added configuration options',
    'widgets/list-popular-blogs/index.tpl' => 'Changed to generic styles',
    'widgets/list-recent-blogs/Controller.php' => 'Added configuration options',
    'widgets/list-recent-blogs/index.tpl' => 'Changed to generic styles',
  ),
  '4.1.1' => array(
    'controllers/AdminSettingsController.php' => 'Newly created categories gets the correct owner id',
    'controllers/IndexController.php' => 'Does not try to populate privacy options if they do not exist on edit page',
    'externals/.htaccess' => 'Added keywords; removed deprecated code',
    'externals/styles/main.css' => 'RTL improvements',
    'settings/changelog.php' => 'Incremented version',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/admin-settings/categories.tpl' => 'Hides the owner id column when viewing categories',
    'views/scripts/index/view.tpl' => 'Fixed issue with building category list',
  ),
  '4.1.0' => array(
    '/application/languages/en/blog.csv' => 'Added phrases',
    'controllers/AdminLevelController.php' => 'Added notice on form save',
    'controllers/AdminManageController.php' => 'Fixed issue with deletion',
    'controllers/AdminSettingsController.php' => 'Added notice on form save',
    'controllers/IndexController.php' => 'Fixed issue with pagination and searching for browse blogs page',
    'externals/images/nophoto_blog_thumb_icon.png' => 'Added',
    'externals/styles/main.css' => 'Added styles',
    'Form/Create.php' => 'Fixed issue with disabled privacy options',
    'Form/Delete.php' => 'Added',
    'Form/Search.php' => 'Fixed issue with disabled privacy options',
    'Plugin/Job/Maintenance/RebuildPrivacy.php' => 'Added',
    'Plugin/Menus.php' => 'Added share link to gutter menu',
    'Plugin/Task/Maintenance/RebuildPrivacy.php' => 'Removed',
    'settings/changelog.php' => 'Incremented version',
    'settings/content.php' => 'Added pagination/item count limits to widgets',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.3-4.0.4.sql' => 'Backwards compatibility fix for tasks modifications',
    'settings/my-upgrade-4.0.5-4.1.0.sql' => 'Added',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/admin-manage/deleteselected.tpl' => 'Removed',
    'views/scripts/admin-manage/index.tpl' => 'Fixed issue with deletion',
    'views/scripts/index/delete.tpl' => 'Removed navigation',
    'views/scripts/index/index.tpl' => 'Fixed issue with pagination; fixed issue with UTF-8 truncation',
    'views/scripts/index/list.tpl' => 'Fixed issues with filtering',
    'views/scripts/index/manage.tpl' => 'Fixed issue with pagination; fixed issue with UTF-8 truncation',
    'views/scripts/index/view.tpl' => 'Fixed issues with filtering',
    'views/scripts/pagination/blogpagination.tpl' => 'Removed',
    'widgets/list-popular-blogs/Controller.php' => 'Added pagination/item count limit',
    'widgets/list-recent-blogs/Controller.php' => 'Added pagination/item count limit',
    'widgets/profile-blogs/Controller.php' => 'Added pagination/item count limit',
    'widgets/profile-blogs/index.tpl' => 'Added pagination/item count limit',
  ),
  '4.0.5' => array(
    'controllers/IndexController.php' => 'Added registered privacy type',
    'Form/Admin/Settings/Level.php' => 'Added registered privacy type',
    'Form/Create.php' => 'Added registered privacy type',
    'Model/Blog.php' => 'Different',
    'Plugin/Task/Maintenance/RebuildPrivacy.php' => 'Added idle support; added registered privacy type',
    'settings/changelog.php' => 'Added',
    'settings/manifest.php' => 'Incremented version',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/index/list.tpl' => 'Added missing css class to navigation',
  ),
  '4.0.4' => array(
    'controllers/IndexController.php' => 'Added localization to the archive list',
    'externals/styles/main.css' => 'Improved RTL support',
    'Form/Style.php' => 'Style tweak',
    'Plugin/Task/Maintenance/RebuildPrivacy.php' => 'Added to fix privacy issues in the feed',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.1-4.0.2.sql' => 'Fixed incorrect admin permissions for commenting',
    'settings/my-upgrade-4.0.3-4.0.4.sql' => 'Added',
    'settings/my.sql' => 'Incremented version',
    'views/scripts/index/index.tpl' => 'Fixes error in blog when filtered by category',
    'views/scripts/index/view.tpl' => 'Fixes style problems in navigation',
    'widgets/list-recent-blogs/index.tpl' => 'Styled',
    'widgets/list-popular-blogs/index.tpl' => 'Styled',
    '/application/languages/en/blog.csv' => 'Added phrases',
  ),
  '4.0.3' => array(
    'controllers/IndexController.php' => 'Menus now use menu system; fixes for auth to allow moderation',
    'Plugin/Menus.php' => 'Menus now use menu system',
    'settings/content.php' => 'Fixed typo in popular blog name which prevented display',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.2-4.0.3.sql' => 'Added',
    'settings/my.sql' => 'Menus now use menu system; incremented version',
    'views/scripts/admin-level/index.tpl' => 'Added missing translation',
    'views/scripts/admin-manage/index.tpl' => 'Fixed view link to use slug; added missing translation; added correct locale date format',
    'views/scripts/admin-settings/categories.tpl' => 'Added missing translation',
    'views/scripts/admin-settings/index.tpl' => 'Added missing translation',
    'views/scripts/index/index.tpl' => 'Menus now use menu system',
    'views/scripts/index/list.tpl' => 'Menus now use menu system',
    'views/scripts/index/manage.tpl' => 'Menus now use menu system; added missing translation',
    'views/scripts/index/view/tpl' => 'Menus now use menu system',
    '/application/languages/en/blog.csv' => 'Added phrases',
  ),
  '4.0.2' => array(
    'Api/Core.php' => 'Categories ordered by name',
    'controllers/AdminLevelController.php' => 'Various level settings fixes and enhancements',
    'Form/Admin/Level.php' => 'Moved',
    'Form/Admin/Settings/Level.php' => 'Various level settings fixes and enhancements',
    'settings/manifest.php' => 'Incremented version',
    'settings/my-upgrade-4.0.1-4.0.2.sql' => 'Added',
    'settings/my.sql' => 'Various level settings fixes and enhancements',
  ),
  '4.0.1' => array(
    'Api/Core.php' => 'Adjustment for trial',
    'controllers/AdminLevelController.php' => 'Fix for public level',
    'controllers/AdminSettingsController.php' => 'Source code formatting',
    'controllers/IndexController.php' => 'Fixed public permissions',
    'Form/Admin/Settings/Global.php' => 'Moved public permissions to public level settings',
    'Form/Admin/Settings/Level.php' => 'Moved public permissions to public level settings',
    'Plugin/Core.php' => 'Query optimization',
    'settings/manifest.php' => 'Incremented version',
    'views/scripts/admin-level/index.tpl' => 'Level change fix',
    'widgets/list-popular-blogs/Controller.php' => 'Fixed typo',
    'widgets/list-recent-blogs/Controller.php' => 'Fixed typo',
    'widgets/list-recent-blogs/index.tpl' => 'Styled',
  ),
) ?>